
version: '3'

services: 
  blackflow-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment: 
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - frontend
      - backend

  blackflow-staging:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=staging
    ports:
      - "3001:3000"
    environment: 
      - NODE_ENV=staging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - staging
      - backend

  blackflow-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment: 
      - NODE_ENV=development
    command: npm run dev
    networks:
      - backend

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - backend

networks:
  frontend:
  backend:
  staging:
  production:
