name: CD

name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: blackflow:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        if_key_exists: replace

    - name: Deploy to EC2
      run: | 
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
          cd ~/app/blackflow
      
          git pull || git clone https://github.com/samif0/blackflow.git .
      
          docker-compose down
          docker-compose up -d blackflow-prod
      
          docker image prune -af 
        ENDSSH
