name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker buildx 
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4 
        with:
          context: .
          load: true
          tags: blackflow:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Lint 
        run: docker run --rm blackflow:test npm run lint
    
      - name: Verify build
        run: echo "✅ Build successful!"
